### ISSUE TITLE
Evalution on real-world objects or datasets

### ISSUE THREAD

**Issue by dingdingcai** [nv-nguyen/nope#1]
Hi,

Thanks for your interesting work! 

I noticed that the evaluation is primarily conducted on synthetic objects. Thus I'd like to ask whether you have tried the proposed method on real-world objects or datasets, for example, on some BOP benchmark datasets.

**Comment by nv-nguyen** [comment]
Hi Dingding,

Thank you for your interest!

I did not but I will definitely try it on BOP benchmarks!
