### ISSUE TITLE
Unable to load the link containing the generation code for the poses

### ISSUE THREAD

**Issue by GokulSoman** [nv-nguyen/nope#10]
Hi,

https://github.com/nv-nguyen/DiffusionPose/blob/52e2c55b065c9637dcd284cc77a0bfb3356d218a/src/poses/find_neighbors.py

Is this file still available to get the code for generation of poses?

Thanks,
Gokul

**Comment by nv-nguyen** [comment]
Hi, the script to generate template poses is available [here](https://github.com/nv-nguyen/gigapose/blob/main/src/lib3d/create_template_poses.py).
