### ISSUE TITLE
Weights availability

### ISSUE THREAD

**Issue by koritsky** [nv-nguyen/nope#3]
Great job!

Are you planning to provide model weights?

**Comment by jerinkantony** [comment]
Yup, weights pls, at least an intermediate one to play with.

**Comment by nv-nguyen** [comment]
[Here](https://drive.google.com/file/d/1fR5SU--Um71mAmtaLGAcSBIZV9c5auta/view?usp=sharing) is the lastest one that I used with vae_base.yaml 
I will release the weights for different configs later.
